# Generated by Django 4.0.2 on 2022-02-17 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_subscription_subscriber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='blog_author',
        ),
        migrations.AddField(
            model_name='subscription',
            name='blog_author',
            field=models.ManyToManyField(related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
