# Generated by Django 4.0.2 on 2022-02-17 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_remove_subscription_blog_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='blog_author',
        ),
        migrations.AddField(
            model_name='subscription',
            name='blog_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
